# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: smartsign

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4

    - name: Download simplysign
      run: >
        curl -O https://files.certum.eu/software/SimplySignDesktop/Windows/9.1.11.61/SimplySignDesktop-9.1.11.61-64-bit-en.msi
    - name: install simplysign
      run: >
        msiexec /i SimplySignDesktop-9.1.11.61-64-bit-en.msi /qn
    - name: launch simplysign
      run: >
        "C:\Program Files\Certum\SimplySign Desktop\SimplySignDesktop.exe"
